services:
  - type: web
    name: proyecto-adbd
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn CV_automatizada.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
