services:
  - type: web
    name: proyecto-adbd
    env: python
    plan: free

    # Build: instalar dependencias del sistema para WeasyPrint + dependencias Python + migraciones
    buildCommand: |
      apt-get update && apt-get install -y libcairo2 libpango1.0-0 libharfbuzz0b libpangoft2-1.0-0
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --no-input
      
    # Start command
    startCommand: gunicorn CV_automatizada.wsgi:application

    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
